  name: bfe
  version: git
  summary: Open-source layer 7 load balancer
  description: |
    BFE is an open-source layer 7 load balancer from Baidu.

  license: Apache-2.0
  base: core18
  grade: stable
  confinement: strict
  architectures:
    - build-on: [amd64, arm64, ppc64el]
  
  parts:
    bfe:
      plugin: go
      go-channel: 1.13/stable
      go-importpath: github.com/bfenetworks/bfe
      source: https://github.com/bfenetworks/bfe.git
      source-type: git
      override-build: | 
        make
        cp -r output/* $SNAPCRAFT_PART_INSTALL/

  apps:
    bfe:
      command: bin/bfe -c $SNAP_COMMON/conf -l $SNAP_COMMON/log
      plugs: [network-bind]
